---
- name: apt-get update
  apt: update_cache=yes

# https://gist.github.com/91e14096374075f5316e
- name: install tmux dependencies
  apt: name={{ item }} state=present
  with_items:
    - python-software-properties
    - software-properties-common

# Add latest tmux repo and update cache again.
- apt_repository: repo='ppa:pi-rho/dev' state=present
- name: apt-get update
  apt: update_cache=yes

- name: install essentials
  apt: name={{ item }} state=latest
  with_items:
    - build-essential
    - libz-dev                      # (also pretty common and essential)
    - libreadline-dev               # (otherwise the REPL prompt can be crap)
    - libncursesw5-dev
    - libssl-dev
    - libgdbm-dev
    - libsqlite3-dev
    - libbz2-dev
    - libc6-dev
    - git
    - tar
    - unzip
    - xclip                         # clipboard..?
    - inotify-tools                 # Some live reloading tools need it
    - silversearcher-ag             # grep/ack replacement
    - exuberant-ctags               # for vim tagbar plugin
    - cmake                         # needed for YCM vim plugin
    - python-dev                    # needed for YCM vim plugin
    - libxml2-utils                 # For xml linting in vim
    - libevent-dev                  # Apparently needed for tmux
    - tmux
    - zsh
    - htop
