---
- name: install basic packages for python environment
  apt: name={{ item }} state=present
  with_items:
    - python-dev
    - python-setuptools
    - python-pip

- name: install virtualenv
  pip: name=virtualenv state=present
