---
# requires {{ swapfile_size }} and {{ swapfile_path }} defined somewhere in vars

# References:
# https://www.digitalocean.com/community/tutorials/how-to-add-swap-on-ubuntu-14-04
# http://stackoverflow.com/questions/24765930/add-swap-memory-with-ansible

- name: Create swap file 2G
  command: fallocate -l {{ swapfile_size }} {{ swapfile_path }}

- name: Set permission on swap file
  file: path={{ swapfile_path }}
        owner=root
        group=root
        mode=0600

- name: Make swap file
  command: mkswap {{ swapfile_path }}

# Make it permanent
- name: Write swap entry in fstab
  mount: name=none
         src={{ swapfile_path }}
         fstype=swap
         opts=sw
         passno=0
         dump=0
         state=present

- name: Mount swap
  command: swapon {{ swapfile_path }}

# Set vm.swappiness to 5 in /etc/sysctl.conf
- sysctl: name=vm.swappiness value=5 state=present

# Set vm.vfs_cache_pressure to 50 in /etc/sysctl.conf
- sysctl: name=vm.vfs_cache_pressure value=50 state=present
