---
# requires virtualenv and {{ venv_dir }} defined

# http://stackoverflow.com/a/21073913/3479934
- name: install additional packages for installing scipy
  apt: name={{ item }} state=present
  with_items:
    - libatlas-base-dev         # need for installing scipy via pip
    - gfortran                  # need for installing scipy via pip
    - libfreetype6-dev          # matplotlib required dependency
    - libxft-dev                # we need it in order to enable matplotlib

- name: install scipy and the whole nine yards
  pip: name={{ item }} state=present
       virtualenv={{ venv_dir }}
  with_items:
    - numpy
    - scipy
    - matplotlib
    - ipython
    - pandas
    - sympy
    - nose
    - scikit-learn
    - pillow                    # scikit-image dependency
    - networkx                  # scikit-image dependency
    - scikit-image
