---
# requires virtualenv and {{ venv_dir }} defined somewhere

- name: install python development tools
  pip: name={{ item }} state=present
       virtualenv={{ venv_dir | default(vagrant_mount_path + "/../venv") }}
  with_items:
    - ipython
    - ipdb

- name: make venv owned by vagrant user
  file: path={{ venv_dir | default(vagrant_mount_path + "/../venv") }} owner=vagrant recurse=yes

- name: install autoenv
  pip: name=autoenv state=present

- name: remove .env file for clean slate
  file: dest={{ vagrant_mount_path }}/.env state=absent
  when: vagrant_mount_path is defined

- name: create .env file inside Vagrant shared folder
  file: dest={{ vagrant_mount_path }}/.env state=touch
  when: vagrant_mount_path is defined
  register: dotenvfile

- name: add virtualenv activate cmd in .env file
  lineinfile: dest={{ dotenvfile.dest }}
              line="source {{ venv_dir | default(vagrant_mount_path + '/../venv') }}/bin/activate"
              state=present
  when: dotenvfile.changed == true
