---
- name: install postgres
  apt: name={{ item }} state=present
  with_items:
    - postgresql
    - postgresql-contrib
    - libpq-dev         # Required for Ansible to interact with postgres
    - python-psycopg2   # Required for Ansible to interact with postgres

# Create superuser vagrant
- postgresql_user: name=vagrant password=vagrant role_attr_flags=SUPERUSER
  become: yes
  become_user: postgres
