---
# Just making sure curl is there
- name: install curl
  apt: name=curl state=present

# Add Docker APT repository and Docker repository GPG key, then update APT sources
- shell: echo deb https://get.docker.io/ubuntu docker main > /etc/apt/sources.list.d/docker.list
- shell: curl -s https://get.docker.io/gpg | sudo apt-key add -
- name: apt-get update
  apt: update_cache=true

# Finally, install Docker
- name: install docker
  apt: name=lxc-docker state=present

