---
# Use n version manager to install node and npm.
# https://github.com/tj/n
# https://github.com/mklement0/n-install
- shell: curl -L http://git.io/n-install | N_PREFIX=/n bash -s -- -y

# XXX: below doesn't really work, better to install in user home folder probably
# need to do it manually.
- name: install node packages globally
  npm: name={{ item }} global=yes
  with_items:
    - eslint
    - eslint-plugin-react
    - babel-eslint
