---
# Maybe use this? Yes, use this.
# http://stackoverflow.com/questions/19451851/install-node-js-to-install-n-to-install-node-js

# https://github.com/nodesource/distributions
# - shell: curl -L https://deb.nodesource.com/setup_4.x | sudo -E bash -
# - name: install nodejs
#   apt: name=nodejs state=present

- name: install node packages globally
  apt: name={{ item }} global=yes
  with_items:
    - eslint
    - eslint-plugin-react
    - babel-eslint
