---
# remote_user: define in inventory

- hosts: web
  sudo: yes

  roles:
    - setup_ubuntu_with_python_basics
    - deploy_app_code_from_git
    - refresh_app_dependencies_python
    - ready_uwsgi_nginx_web_service

